FROM ros:humble

SHELL ["/bin/bash", "-c"]

# Update to latest version
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="Europe/London"
RUN apt-get update

# install ros package
RUN apt-get update && apt-get install -y \
      ros-${ROS_DISTRO}-desktop \
      ros-${ROS_DISTRO}-demo-nodes-cpp \
      ros-${ROS_DISTRO}-demo-nodes-py

WORKDIR /root

RUN mkdir -p ~/plansys2_ws/src && \
    cd ~/plansys2_ws/src && \
    git clone https://github.com/PlanSys2/ros2_planning_system.git && \
    cd ros2_planning_system && \
    git checkout ${ROS_DISTRO}-devel

RUN cd ~/plansys2_ws && rosdep install -y -r -q --from-paths src --ignore-src --rosdistro ${ROS_DISTRO}

RUN cd ~/plansys2_ws/src && \
    git clone https://github.com/PlanSys2/ros2_planning_system_examples.git && \
    cd ros2_planning_system_examples && \
    git checkout ${ROS_DISTRO}

RUN cd ~/plansys2_ws && rosdep install -y -r -q --from-paths src --ignore-src --rosdistro ${ROS_DISTRO}

RUN apt-get install -y vim gdb terminator

RUN cd ~/plansys2_ws && source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --symlink-install --executor sequential

CMD /bin/bash


# ---- to run on MacOS ------------

# docker run -v.:/computer --network=host --name ubuntu_bash --privileged --shm-size 2g --rm -i -t ros-humble bash 

# cp -r /computer/assignments/pb5/plansys2_healthcare_pb5/ /root/plansys2_ws/src/ros2_planning_system_examples/

# cd /root/plansys2_ws/
# colcon build --symlink-install
# rosdep install --from-paths src/ros2_planning_system_examples/plansys2_healthcare_pb5/ --ignore-src -r -y
# colcon build --symlink-install

# source /opt/ros/humble/setup.bash
# source ~/plansys2_ws/install/setup.bash

# ros2 launch plansys2_healthcare_pb5 plansys2_healthcare_pb5_launch.py

#  ---- new terminal

# docker exec -it CONTAINER_ID bash

# source ~/plansys2_ws/install/setup.bash
# ros2 run plansys2_terminal plansys2_terminal

# ------ plansys2 terminal

# source plansys2_ws/src/ros2_planning_system_examples/plansys2_healthcare_pb5/launch/commands.txt
# get plan
# run

# -----------------------------

# to build
# sudo docker build --rm  --tag ros-humble . --file Dockerfile-humble

# to run
# sudo docker run -v /tmp/.X11-unix/:/tmp/.X11-unix/ --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --network=host --name ubuntu_bash --env="DISPLAY" --rm -i -t ros-humble bash

# Or
# sudo docker run -v /tmp/.X11-unix/:/tmp/.X11-unix/ --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --network=host --name ubuntu_bash --env="DISPLAY" --rm -i -t docker.io/library/ros-humble:latest bash 



